# Configurations
dist: bionic
language: python
python:
  - "3.9.5"

before_deploy:
  - pyenv global 3.9.5
  - pip install cloudsmith-cli poetry
  - poetry install --no-root
  - poetry build

deploy:
  provider: script
  skip_cleanup: true
  script: cloudsmith push python --republish proglove/python-packages dist/bleak_proglove-*.whl
  on:
    branch: proglove_next

